name: Quality & Security Checks2

on:
  push:
    branches: [feature/workflows]
  pull_request:
    branches: [feature/workflows]

jobs:
  test-and-security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Run npm audit
        run: npm audit --audit-level=high

      - name: Run unit/integration tests with coverage
        run: npm run test

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
